# Generated by Django 2.1.15 on 2021-01-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='site_id',
            field=models.IntegerField(default=0),
        ),
    ]
