# Generated by Django 2.1.15 on 2021-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wave_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='site_id',
            field=models.CharField(max_length=8),
        ),
    ]
