# Generated by Django 2.1.15 on 2021-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210110_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='awesome_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wave',
            name='in_level',
            field=models.IntegerField(default=0),
        ),
    ]
