# Generated by Django 2.1.15 on 2021-01-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wave_wave_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wave',
            name='wave_name',
        ),
    ]
