# Generated by Django 2.1.15 on 2021-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_wave_wave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='nws_gage',
            field=models.CharField(default='0000', max_length=9),
        ),
        migrations.AlterField(
            model_name='wave',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='wave',
            name='site_id',
            field=models.CharField(max_length=9),
        ),
    ]
